use_frameworks!

platform :ios, '9.0'

target 'NETPPTDownloadHandler_Example' do
  pod 'NETPPTDownloadHandler', :path => '../'

  target 'NETPPTDownloadHandler_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
